import subprocess
import re
import csv
import os
import argparse
import concurrent.futures
import datetime


def strip_ansi(text):
    """Removes ANSI color codes generated by rich to ensure clean regex matching."""
    if text is None:
        return ""
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)


def generate_constraint(pharms, weeks):
    """Helper to generate constraint strings (e.g., '1,1;1,2;2,1;2,2')"""
    if not pharms: return ""
    return ";".join([f"{p},{w}" for p in pharms for w in weeks])


def execute_and_parse(task):
    """Function to be run by worker threads or sequentially."""
    cmd = task['cmd']
    run_type = task['run_type']
    desc = task['desc']
    
    year_match = re.search(r'--year (\d+)', cmd)
    year = int(year_match.group(1)) if year_match else "N/A"
    
    tl_match = re.search(r'--time-limit (\d+)', cmd)
    time_limit = int(tl_match.group(1)) if tl_match else "N/A"
    
    print(f"  [STARTING] Run: {run_type} | TL: {time_limit}s | Desc: {desc}")
    
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, encoding='utf-8', errors='replace')
    raw_output = strip_ansi(result.stdout)
    
    farmacia_matches = re.findall(r'│\s*(F\d+)\s*│\s*(\d+)\s*│', raw_output)
    totale_match = re.search(r'Totale complessivo turni assegnati:\s*(\d+)', raw_output)
    media_match = re.search(r'Media farmacie per settimana:\s*([\d\.]+)', raw_output)
    ottimizzazione_match = re.search(r'Valore di Ottimizzazione.*?:\s*(\d+)', raw_output)
    time_match = re.search(r'Computation time: \s*([\d\.]+) seconds', raw_output, re.IGNORECASE)
    
    totale = totale_match.group(1) if totale_match else "N/A"
    media = media_match.group(1) if media_match else "N/A"
    ottimizzazione = ottimizzazione_match.group(1) if ottimizzazione_match else "N/A"
    comp_time = time_match.group(1) if time_match else "N/A"
    
    # 1. Save detailed breakdown for this specific run
    csv_filename = f"run_results/{run_type}_{time_limit}.csv"
    local_master_data = []
    
    with open(csv_filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['Farmacia', 'Turni Assegnati'])
        
        for farmacia, turni in farmacia_matches:
            writer.writerow([farmacia, turni])
            local_master_data.append([
                year, time_limit, run_type, desc, farmacia, turni,
                totale, media, ottimizzazione, comp_time
            ])
        
        writer.writerow([])
        writer.writerow(['Metrica', 'Valore'])
        writer.writerow(['Totale complessivo turni assegnati', totale])
        writer.writerow(['Media farmacie per settimana', media])
        writer.writerow(['Valore di Ottimizzazione', ottimizzazione])
        writer.writerow(['Computation time (seconds)', comp_time])
        writer.writerow(['Constraint Description', desc])
    
    print(f"  [FINISHED] Run: {run_type} | TL: {time_limit}s")
    
    return {
        "run_type": run_type,
        "is_base": task.get('is_base', False),
        "year": year,
        "time_limit": time_limit,
        "ottimizzazione": ottimizzazione,
        "master_rows": local_master_data
    }


def main():
    parser = argparse.ArgumentParser(description="Run scheduling optimization commands and parse output.")
    parser.add_argument('--parallel', action='store_true',
                        help="Run time-limit batches in parallel (default: False/Sequential)")
    args = parser.parse_args()
    
    time_limits = [15, 30, 45, 60]
    tasks_grouped = []
    
    # --- 1. Base Years (2024 - 2027) ---
    for y in [2024, 2025, 2026, 2027]:
        group = []
        for tl in time_limits:
            prev_str = f" --prev-year test{y - 1}_{tl}.csv" if y > 2024 else ""
            cmd = f"python rich_runner.py --auto-festivities --csv-mode compact --csv test{y}_{tl}.csv --year {y} --time-limit {tl}{prev_str}"
            group.append({
                "cmd": cmd, "run_type": f"Base_{y}", "desc": f"Base Run for {y} without constraints",
                "group_name": f"Base {y}", "is_base": True
            })
        tasks_grouped.append(group)
    
    # --- 2. Reschedule & Corrected 2026 ---
    grp_resched = []
    grp_corrected = []
    for tl in time_limits:
        grp_resched.append({
            "cmd": f"python rich_runner.py --year 2026 --prev-year schedule_2025.csv --reschedule-csv schedule_2026.csv --reschedule-from now --auto-festivities --csv-mode compact --csv rescheduled2026_{tl}.csv --time-limit {tl}",
            "run_type": "Reschedule_2026", "desc": "Reschedule from now based on schedule_2026.csv",
            "group_name": "Reschedule 2026"
        })
        grp_corrected.append({
            "cmd": f"python rich_runner.py --year 2026 --prev-year schedule_2025.csv --auto-festivities --csv-mode compact --csv corrected2026_{tl}.csv --time-limit {tl}",
            "run_type": "Corrected_2026", "desc": "Corrected 2026 based on schedule_2025.csv",
            "group_name": "Corrected 2026"
        })
    tasks_grouped.extend([grp_resched, grp_corrected])
    
    # --- 3. Dynamic Constraint Scenarios for 2026 ---
    fc_weeks = list(range(22, 30))  # Weeks 22-29 (8 weeks mid-year)
    pc_weeks = list(range(32, 34))  # Weeks 32-33 (2 weeks mid-year)
    
    # Configuration definitions: Center = 1-6, Marina = 7-10
    constraint_configs = [
        # Forced Closed Only (8 weeks)
        {"name": "FC_1C", "fc": [1], "pc": [], "desc": "1 FC Center (8w)"},
        {"name": "FC_2C", "fc": [1, 2], "pc": [], "desc": "2 FC Center (8w)"},
        {"name": "FC_3C", "fc": [1, 2, 3], "pc": [], "desc": "3 FC Center (8w)"},
        {"name": "FC_1M", "fc": [7], "pc": [], "desc": "1 FC Marina (8w)"},
        {"name": "FC_2M", "fc": [7, 8], "pc": [], "desc": "2 FC Marina (8w)"},
        {"name": "FC_1C_1M", "fc": [1, 7], "pc": [], "desc": "1 FC Center, 1 FC Marina (8w)"},
        {"name": "FC_2C_1M", "fc": [1, 2, 7], "pc": [], "desc": "2 FC Center, 1 FC Marina (8w)"},
        
        # Pref Closed Only (2 weeks)
        {"name": "PC_1C", "fc": [], "pc": [4], "desc": "1 PC Center (2w)"},
        {"name": "PC_2C", "fc": [], "pc": [4, 5], "desc": "2 PC Center (2w)"},
        {"name": "PC_3C", "fc": [], "pc": [4, 5, 6], "desc": "3 PC Center (2w)"},
        {"name": "PC_4C", "fc": [], "pc": [1, 2, 3, 4], "desc": "4 PC Center (2w)"},
        {"name": "PC_1M", "fc": [], "pc": [9], "desc": "1 PC Marina (2w)"},
        {"name": "PC_2M", "fc": [], "pc": [9, 10], "desc": "2 PC Marina (2w)"},
        {"name": "PC_1C_1M", "fc": [], "pc": [4, 9], "desc": "1 PC Center, 1 PC Marina (2w)"},
        {"name": "PC_2C_1M", "fc": [], "pc": [4, 5, 9], "desc": "2 PC Center, 1 PC Marina (2w)"},
        {"name": "PC_3C_1M", "fc": [], "pc": [4, 5, 6, 9], "desc": "3 PC Center, 1 PC Marina (2w)"},
        {"name": "PC_1C_2M", "fc": [], "pc": [4, 9, 10], "desc": "1 PC Center, 2 PC Marina (2w)"},
        {"name": "PC_2C_2M", "fc": [], "pc": [4, 5, 9, 10], "desc": "2 PC Center, 2 PC Marina (2w)"},
        {"name": "PC_3C_2M", "fc": [], "pc": [4, 5, 6, 9, 10], "desc": "3 PC Center, 2 PC Marina (2w)"},
        
        # Combined (FC=8 weeks, PC=2 weeks)
        {"name": "Comb_1FC_1PC_C", "fc": [1], "pc": [4], "desc": "1 FC C + 1 PC C"},
        {"name": "Comb_2FC_1PC_C", "fc": [1, 2], "pc": [4], "desc": "2 FC C + 1 PC C"},
        {"name": "Comb_1FC_2PC_C", "fc": [1], "pc": [4, 5], "desc": "1 FC C + 2 PC C"},
        {"name": "Comb_2FC_2PC_C", "fc": [1, 2], "pc": [4, 5], "desc": "2 FC C + 2 PC C"},
        {"name": "Comb_1FC_1PC_M", "fc": [7], "pc": [9], "desc": "1 FC M + 1 PC M"},
        {"name": "Comb_1F_1M_1P_1PM", "fc": [1, 7], "pc": [4, 9], "desc": "1 FC C + 1 FC M + 1 PC C + 1 PC M"},
        {"name": "Comb_2F_1M_1P_1PM", "fc": [1, 2, 7], "pc": [4, 9], "desc": "2 FC C + 1 FC M + 1 PC C + 1 PC M"},
        {"name": "Comb_1F_1M_2P_1PM", "fc": [1, 7], "pc": [4, 5, 9], "desc": "1 FC C + 1 FC M + 2 PC C + 1 PC M"},
        {"name": "Comb_2F_1M_2P_1PM", "fc": [1, 2, 7], "pc": [4, 5, 9], "desc": "2 FC C + 1 FC M + 2 PC C + 1 PC M"},
    ]
    
    for config in constraint_configs:
        group = []
        fc_str = generate_constraint(config["fc"], fc_weeks)
        pc_str = generate_constraint(config["pc"], pc_weeks)
        
        for tl in time_limits:
            cmd = f"python rich_runner.py --auto-festivities --csv-mode compact --csv constraint_{config['name']}_{tl}.csv --year 2026 --time-limit {tl} --prev-year test2025_{tl}.csv"
            if fc_str:
                cmd += f' --force-closed "{fc_str}"'
            if pc_str:
                cmd += f' --pref-closed "{pc_str}"'
            
            group.append({
                "cmd": cmd, "run_type": f"Constraint_{config['name']}", "desc": config["desc"],
                "group_name": f"Constraints: {config['desc']}"
            })
        tasks_grouped.append(group)
    
    # Data collections
    summary_matrix = {}  # Only stores Base runs for the matrix file
    master_csv_data = []
    
    os.makedirs("run_results", exist_ok=True)
    print(f"Execution Mode: {'PARALLEL' if args.parallel else 'SEQUENTIAL'}\n")
    
    for group in tasks_grouped:
        group_title = group[0]['group_name']
        print(f"--- Initiating Batch: {group_title} ---")
        
        if args.parallel:
            with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
                future_to_task = {executor.submit(execute_and_parse, task): task for task in group}
                for future in concurrent.futures.as_completed(future_to_task):
                    result_data = future.result()
                    master_csv_data.extend(result_data["master_rows"])
                    
                    if result_data["is_base"]:
                        summary_matrix[(result_data["year"], result_data["time_limit"])] = result_data["ottimizzazione"]
        else:
            for task in group:
                result_data = execute_and_parse(task)
                master_csv_data.extend(result_data["master_rows"])
                
                if result_data["is_base"]:
                    summary_matrix[(result_data["year"], result_data["time_limit"])] = result_data["ottimizzazione"]
    
    print("\nAll batches complete! Generating final summary reports...")
    
    # Save the final Master CSV Report (Contains ALL runs, deeply documented)
    master_filename = "master_report_all_data.csv"
    with open(master_filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['Year', 'Time_Limit_sec', 'Run_Type', 'Constraint_Description', 'Farmacia', 'Turni_Assegnati',
                         'Totale_Turni_Complessivo', 'Media_Per_Settimana', 'Valore_Ottimizzazione',
                         'Computation_Time_sec'])
        writer.writerows(master_csv_data)
    
    print(f"Master CSV with full documentation saved to '{master_filename}'.")
    
    # Save the final summary matrix (Contains only base runs 2024-2027)
    summary_filename = "valore_di_ottimizzazione_matrix.csv"
    years = [2024, 2025, 2026, 2027]
    with open(summary_filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow([''] + [str(y) for y in years])
        
        for tl in time_limits:
            row = [str(tl)]
            for y in years:
                row.append(summary_matrix.get((y, tl), ''))
            writer.writerow(row)
    
    print(f"Summary matrix saved to '{summary_filename}'.")
    
    # Generate Markdown Report Document
    report_filename = "report.md"
    with open(report_filename, "w", encoding="utf-8") as rf:
        rf.write("# Scheduling Execution Report\n\n")
        rf.write(f"**Date Generated:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        rf.write("## Week Configurations (Mid-Year Simulation)\n")
        rf.write(f"- **Forced Closed (FC) Weeks (8 weeks):** Weeks {fc_weeks[0]} to {fc_weeks[-1]}\n")
        rf.write(f"- **Preferably Closed (PC) Weeks (2 weeks):** Weeks {pc_weeks[0]} to {pc_weeks[-1]}\n\n")
        
        rf.write("## Constraint Scenarios\n")
        rf.write("| Scenario Name | Description | FC Pharmacies | PC Pharmacies |\n")
        rf.write("|---|---|---|---|\n")
        
        for config in constraint_configs:
            fc_list = ", ".join(map(str, config['fc'])) if config['fc'] else "None"
            pc_list = ", ".join(map(str, config['pc'])) if config['pc'] else "None"
            rf.write(f"| {config['name']} | {config['desc']} | {fc_list} | {pc_list} |\n")
    
    print(f"Markdown documentation report saved to '{report_filename}'.")


if __name__ == "__main__":
    main()
