import subprocess
import re
import csv
import os
import argparse
import concurrent.futures

def strip_ansi(text):
    """Removes ANSI color codes generated by rich to ensure clean regex matching."""
    if text is None:
        return ""
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)

def execute_and_parse(cmd):
    """Function to be run by worker threads or sequentially."""
    year_match = re.search(r'--year (\d+)', cmd)
    year = int(year_match.group(1)) if year_match else "N/A"
    
    tl_match = re.search(r'--time-limit (\d+)', cmd)
    time_limit = int(tl_match.group(1)) if tl_match else "N/A"
    
    is_reschedule = "--reschedule-csv" in cmd
    run_type = "Reschedule" if is_reschedule else "Normal"
    
    print(f"  [STARTING] Year: {year} | Time Limit: {time_limit} | Type: {run_type}")
    
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, encoding='utf-8', errors='replace')
    raw_output = strip_ansi(result.stdout)

    farmacia_matches = re.findall(r'│\s*(F\d+)\s*│\s*(\d+)\s*│', raw_output)
    totale_match = re.search(r'Totale complessivo turni assegnati:\s*(\d+)', raw_output)
    media_match = re.search(r'Media farmacie per settimana:\s*([\d\.]+)', raw_output)
    ottimizzazione_match = re.search(r'Valore di Ottimizzazione.*?:\s*(\d+)', raw_output)
    
    time_match = re.search(r'Computation time: \s*([\d\.]+) seconds', raw_output, re.IGNORECASE)

    totale = totale_match.group(1) if totale_match else "N/A"
    media = media_match.group(1) if media_match else "N/A"
    ottimizzazione = ottimizzazione_match.group(1) if ottimizzazione_match else "N/A"
    comp_time = time_match.group(1) if time_match else "N/A"

    prefix = "reschedule" if is_reschedule else "details"
    csv_filename = f"run_results/{prefix}_{year}_{time_limit}.csv"
    
    local_master_data = []
    
    with open(csv_filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['Farmacia', 'Turni Assegnati'])
        
        for farmacia, turni in farmacia_matches:
            writer.writerow([farmacia, turni])
            local_master_data.append([
                year, time_limit, run_type, farmacia, turni, 
                totale, media, ottimizzazione, comp_time
            ])
        
        writer.writerow([])
        writer.writerow(['Metrica', 'Valore'])
        writer.writerow(['Totale complessivo turni assegnati', totale])
        writer.writerow(['Media farmacie per settimana', media])
        writer.writerow(['Valore di Ottimizzazione', ottimizzazione])
        writer.writerow(['Computation time (seconds)', comp_time])

    print(f"  [FINISHED] Year: {year} | Time Limit: {time_limit} | Type: {run_type}")
    
    return {
        "is_reschedule": is_reschedule,
        "year": year,
        "time_limit": time_limit,
        "ottimizzazione": ottimizzazione,
        "master_rows": local_master_data
    }

def main():
    parser = argparse.ArgumentParser(description="Run scheduling optimization commands and parse output.")
    parser.add_argument('--parallel', action='store_true', help="Run time-limit batches in parallel (default: False/Sequential)")
    args = parser.parse_args()

    command_groups = [
        # Group 1: 2024
        [
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2024_15.csv --year 2024 --time-limit 15",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2024_30.csv --year 2024 --time-limit 30",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2024_45.csv --year 2024 --time-limit 45",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2024_60.csv --year 2024 --time-limit 60"
        ],
        # Group 2: 2025
        [
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2025_15.csv --year 2025 --time-limit 15 --prev-year test2024_15.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2025_30.csv --year 2025 --time-limit 30 --prev-year test2024_30.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2025_45.csv --year 2025 --time-limit 45 --prev-year test2024_45.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2025_60.csv --year 2025 --time-limit 60 --prev-year test2024_60.csv"
        ],
        # Group 3: 2026
        [
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2026_15.csv --year 2026 --time-limit 15 --prev-year test2025_15.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2026_30.csv --year 2026 --time-limit 30 --prev-year test2025_30.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2026_45.csv --year 2026 --time-limit 45 --prev-year test2025_45.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2026_60.csv --year 2026 --time-limit 60 --prev-year test2025_60.csv"
        ],
        # Group 4: 2027
        [
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2027_15.csv --year 2027 --time-limit 15 --prev-year test2026_15.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2027_30.csv --year 2027 --time-limit 30 --prev-year test2026_30.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2027_45.csv --year 2027 --time-limit 45 --prev-year test2026_45.csv",
            "python rich_runner.py --auto-festivities --csv-mode compact --csv test2027_60.csv --year 2027 --time-limit 60 --prev-year test2026_60.csv"
        ],
        # Group 5: Reschedule Tests
        [
            "python rich_runner.py --year 2026 --prev-year schedule_2025.csv --reschedule-csv schedule_2026.csv --reschedule-from now --auto-festivities --csv-mode compact --csv rescheduled2026_15.csv --time-limit 15",
            "python rich_runner.py --year 2026 --prev-year schedule_2025.csv --reschedule-csv schedule_2026.csv --reschedule-from now --auto-festivities --csv-mode compact --csv rescheduled2026_30.csv --time-limit 30",
            "python rich_runner.py --year 2026 --prev-year schedule_2025.csv --reschedule-csv schedule_2026.csv --reschedule-from now --auto-festivities --csv-mode compact --csv rescheduled2026_45.csv --time-limit 45",
            "python rich_runner.py --year 2026 --prev-year schedule_2025.csv --reschedule-csv schedule_2026.csv --reschedule-from now --auto-festivities --csv-mode compact --csv rescheduled2026_60.csv --time-limit 60"
        ]
    ]

    summary_matrix = {}
    years = [2024, 2025, 2026, 2027]
    time_limits = [15, 30, 45, 60]
    master_csv_data = []

    os.makedirs("run_results", exist_ok=True)

    print(f"Execution Mode: {'PARALLEL' if args.parallel else 'SEQUENTIAL'}")

    for i, group in enumerate(command_groups):
        group_name = "Reschedule Tests" if i == 4 else f"Year {2024 + i}"
        print(f"\n--- Initiating Batch: {group_name} ---")
        
        if args.parallel:
            with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
                future_to_cmd = {executor.submit(execute_and_parse, cmd): cmd for cmd in group}
                
                for future in concurrent.futures.as_completed(future_to_cmd):
                    result_data = future.result()
                    master_csv_data.extend(result_data["master_rows"])
                    
                    if not result_data["is_reschedule"] and result_data["ottimizzazione"] != "N/A":
                        summary_matrix[(result_data["year"], result_data["time_limit"])] = result_data["ottimizzazione"]
        else:
            for cmd in group:
                result_data = execute_and_parse(cmd)
                master_csv_data.extend(result_data["master_rows"])
                
                if not result_data["is_reschedule"] and result_data["ottimizzazione"] != "N/A":
                    summary_matrix[(result_data["year"], result_data["time_limit"])] = result_data["ottimizzazione"]

    print("\nAll batches complete! Generating final summary reports...")

    master_filename = "master_report_all_data.csv"
    with open(master_filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['Year', 'Time_Limit_sec', 'Run_Type', 'Farmacia', 'Turni_Assegnati', 
                         'Totale_Turni_Complessivo', 'Media_Per_Settimana', 'Valore_Ottimizzazione', 'Computation_Time_sec'])
        writer.writerows(master_csv_data)
        
    print(f"Master CSV with all combined data saved to '{master_filename}'.")

    summary_filename = "valore_di_ottimizzazione_matrix.csv"
    with open(summary_filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        
        header = [''] + [str(y) for y in years]
        writer.writerow(header)
        
        for tl in time_limits:
            row = [str(tl)]
            for y in years:
                val = summary_matrix.get((y, tl), '')
                row.append(val)
            writer.writerow(row)
            
    print(f"Summary matrix saved to '{summary_filename}'.")

if __name__ == "__main__":
    main()